language: python

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.10.0
    - LATEST_WORDPRESS=4
    - LATEST_NGINX=1.13
  matrix:
    - WORDPRESS=4 NGINX=1.13
    - WORDPRESS=4 NGINX=1.12

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - cd ./$WORDPRESS/$NGINX
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make VERSION="$WORDPRESS-$NGINX-$TRAVIS_TAG" release
    fi

    if [ "$WORDPRESS" == "$LATEST_WORDPRESS" && "$NGINX" == "$LATEST_NGINX" ]; then
      make VERSION=latest release
    fi
  fi

after_failure:
  - make logs